// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "forumless/app/models"

	mock "github.com/stretchr/testify/mock"
)

// Iface is an autogenerated mock type for the Iface type
type Iface struct {
	mock.Mock
}

// CreateComment provides a mock function with given fields: user, comment
func (_m *Iface) CreateComment(user models.User, comment models.Comment) error {
	ret := _m.Called(user, comment)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.User, models.Comment) error); ok {
		r0 = rf(user, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePost provides a mock function with given fields: user, post
func (_m *Iface) CreatePost(user models.User, post models.Post) error {
	ret := _m.Called(user, post)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.User, models.Post) error); ok {
		r0 = rf(user, post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: user
func (_m *Iface) CreateUser(user models.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
