// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	models "forumless/app/models"

	mock "github.com/stretchr/testify/mock"
)

// Iface is an autogenerated mock type for the Iface type
type Iface struct {
	mock.Mock
}

// CreateComment provides a mock function with given fields: user, comment
func (_m *Iface) CreateComment(user models.User, comment models.Comment) {
	_m.Called(user, comment)
}

// CreatePost provides a mock function with given fields: user, post
func (_m *Iface) CreatePost(user models.User, post models.Post) error {
	ret := _m.Called(user, post)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.User, models.Post) error); ok {
		r0 = rf(user, post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: name
func (_m *Iface) CreateUser(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
